### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by IonicSyz1823** [Eric-pm-pl/MultiPlayerCounter#34]
**Describe the bug**
Error appears on startup. I have the libpmquery install along with devieron

**To Reproduce**

**Expected behavior**
Errors display on startup

**Screenshots**
![image](https://user-images.githubusercontent.com/38596154/182190604-4fd8f10a-2b87-4ee9-b513-e036c2163c8b.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 0xliam627** [comment]
Please download phar on poggit!
