### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by ghost** [Eric-pm-pl/MultiPlayerCounter#48]
![Screenshot_20220831-203905](https://user-images.githubusercontent.com/100979680/187803388-94628181-b421-4d56-a8e7-36a67ae0aaba.png)

**Comment by 0xliam627** [comment]
As it said: "server failed to respond" please check the config and connect server again.

**Comment by ghost** [comment]
settings are all right, there is nothing wrong, how to fix? 

> As it said: "server failed to respond" please check the config and connect server again.

**Comment by ghost** [comment]
The configuration you speak is basically putting the IP and port of the server? :v
