### ISSUE TITLE
question

### ISSUE THREAD

**Issue by jaylac2000** [Eric-pm-pl/MultiPlayerCounter#5]
Does this plugin need to be on all the servers??

Currently I have it only on my Hub but its not showing the other servers players even though I have edited the config to the other server

![image](https://user-images.githubusercontent.com/53111006/165293556-9463c751-7c8b-448e-be90-459df89c5a6c.png)
![image](https://user-images.githubusercontent.com/53111006/165293805-b2c287d4-805f-46d7-986f-0d4b7d0f6047.png)

**Comment by 0xliam627** [comment]
> Does this plugin need to be on all the servers??
> 
> Currently I have it only on my Hub but its not showing the other servers players even though I have edited the config to the other server

You just need to put it on 1 Lobby server

**Comment by jaylac2000** [comment]
Ok, thank you.

It doesn't appear to give player count or max count between all servers.

Any ideas?

**Comment by 0xliam627** [comment]
> Ok, thank you.
> 
> It doesn't appear to give player count or max count between all servers.
> 
> Any ideas?

Have you installed jasonwynn10's libpmquery? if so, please adjust the update time in the config and check again

**Comment by jaylac2000** [comment]
I haven't... 
![image](https://user-images.githubusercontent.com/53111006/165296727-8c44a4f6-0326-4254-98d7-e3ce2db4e2a8.png)

**Comment by jaylac2000** [comment]
However I see its a virion. Which you have in poggit file which should auto inject it through poggit ci
![image](https://user-images.githubusercontent.com/53111006/165297011-f085dead-343e-439f-8a45-4a84f513e595.png)

**Comment by 0xliam627** [comment]
> However I see its a virion. Which you have in poggit file which should auto inject it through poggit ci ![image](https://user-images.githubusercontent.com/53111006/165297011-f085dead-343e-439f-8a45-4a84f513e595.png)

https://github.com/jasonwynn10/libpmquery

**Comment by jaylac2000** [comment]
Shouldn't it already be injected with Poggit CI?

**Comment by 0xliam627** [comment]
> Referen

why ?

**Comment by jaylac2000** [comment]
the virion should already be injected with poggit..

**Comment by jaylac2000** [comment]
@DavidGlitch04 can you note the plugin is tested and not working... I am using [NaviCompass](https://poggit.pmmp.io/p/NaviCompass/3.0.3) which is working perfectly fine... So it is a bug with this plugin
![image](https://user-images.githubusercontent.com/53111006/165447976-de419cc1-de3c-48df-8658-d1c9b288ae5a.png)
Note that's fake numbers under the factions one. the skyblock one is legit and at 0 players online

**Comment by 0xliam627** [comment]
It works great for me other plugins have no effect on it
