### ISSUE TITLE
HOW TO install libpmquerry??!?!?!

### ISSUE THREAD

**Issue by TheRealDeveloper** [Eric-pm-pl/MultiPlayerCounter#8]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by NhanAZ** [comment]
I think you should download MultiPlayerCounter.phar here
https://github.com/David-pm-pl/MultiPlayerCounter/releases/tag/v0.0.4

**Comment by 0xliam627** [comment]
Download DEVirion plugin and restart server to get virions folder then download libpmquery at https://github.com/jasonwynn10/libpmquery and extract to Your_Server/virions folder
